const express=require("express")
const router=express.Router()
const {allBanners,addBanners,editBanner,addBannersSettings,getOne,uploadPic,deleteBanner,getOneBanner,isActiveBanner, isActiveBanners}=require("../contollers/bannerController")
router.get("/",allBanners)
router.get("/getOne",getOne)
router.get("/getOneBanner",getOneBanner)
router.post("/addBanner",addBanners)
router.post("/editBanner",editBanner)
router.post("/uploadPic",uploadPic)
router.get("/bannerSetting",addBannersSettings)
router.post("/isActiveBanner",isActiveBanners)
router.delete("/",deleteBanner)
module.exports=router