const express=require("express")
const router=express.Router()
const{allConstructors,addConstructor,addSubcategory,getOneSubcategory,editSubcategory,deleteConstructor,getOneConstructor,addPic,getOneConstructorSimple,
editConstructor,deleteSubcategory,addVideo, allConstructorsPro,addTestPic,addFile,deleteFile,search}=require("../contollers/constructorController")
router.get("/",allConstructors)
router.get("/all",allConstructorsPro)
router.get("/getOne",getOneConstructor)
router.get("/getOneSimple",getOneConstructorSimple)
router.post("/edit",editConstructor)
router.post("/",addConstructor)
router.delete("/",deleteConstructor)
router.delete("/deleteFile",deleteFile)
router.post("/subCategory",addSubcategory)
router.get("/subCategory/getOne",getOneSubcategory)
router.post("/subCategory/edit",editSubcategory)
router.delete("/subCategory",deleteSubcategory)
router.post("/addVideo",addVideo)
router.post("/addPic",addPic)
router.post("/addFile",addFile)
router.get("/searchAdmin",search)
module.exports=router